### ISSUE TITLE
[Feature Request] - Add support for fireplaces

### ISSUE THREAD

**Issue by niemyjski** [nguyer/homeassistant-bond-home#1]
Add support for fireplaces http://docs-local.appbond.com/#tag/Devices

**Comment by nguyer** [comment]
Good point. I will definitely work on this when I get a chance. I don't have an RF fireplace to test with myself. If you have one, do you mind sharing what actions yours supports? I see `SetFlame`, `IncreaseFlame` and `DecreaseFlame` in the docs, but I'm wondering what other things like `TurnOn`, `TurnOff` and `TogglePower` they might implement.

If you do a `GET` on `http://{bondIp}/v2/devices/{deviceId}` you can get a list of the actions it supports. Or you can use the Python library and call `getDevice(deviceId)`

**Comment by niemyjski** [comment]
I have Turn on, off, flame up and down. Would be super nice to enumerate all devices and then get all states and then just automatically create entities for each state dynamically using the state name as a suffix.

```json
{"name":"Fireplace","type":"FP","location":"Living Room","actions":["IncreaseFlame","TurnOn","TurnOff","DecreaseFlame","Stop","TogglePower","SetFlame"],"_":"2acd21ff","commands":{"_":"b172eef0"},"state":{"_":"fb9a8ae1"},"properties":{"_":"9bdfb59f"}}
```

**Comment by niemyjski** [comment]
https://github.com/nguyer/homeassistant-bond-home/pull/13
