### ISSUE TITLE
'Bond' object has no attribute 'turnFanOn’ 

### ISSUE THREAD

**Issue by publicpersona31** [nguyer/homeassistant-bond-home#10]
Added the component through HACS, added the config to my `configuration.yaml`

My ceiling fan with integrated light shows up with both a `light.ceiling_fan` and `fan.ceiling_fan` entity.  I can turn the light on/off no problem.  However if I call `fan.turn_on` . I get an error:
```
'Bond' object has no attribute 'turnFanOn'
```
looking through `bond.py` the `Bond` class does not define `turnFanOn`...

Same issue with 'turnFanOff'

**Comment by spelliott7** [comment]
I don't think it's been added.  The readme had "This is still in the very early stages of development, and so far only turning lights on and off is the only thing that actually works. "

I'm really interested, especially now that there are API's on the Bond. It's the only one that controls my 303mghz so I had few options.

**Comment by publicpersona31** [comment]
the author explained that it was an error in the bond.py version he uploaded.  Specifying the earlier library fixes it and it works with both lights and fans.

**Comment by niemyjski** [comment]
Is there any updates on this? Looks like there are a bunch of open pr's.

**Comment by publicpersona31** [comment]
I believe it works now.  The author reverted back to bond-home==0.0.4 in the manifest.json file, which fixed the bug, at least for me.  It controls both my fans/lights perfectly.

**Comment by ViolentPoo** [comment]
“It controls both my fans/lights perfectly.”
Do your fans not have adjustable speeds? Just calling for a ceiling fan to turn on without being able to adjust its speed also is not what most would consider “perfect”

**Comment by spelliott7** [comment]
You can use automation to call REST commands for that if you want. Similar to the way you get the Bond Token you can use commands for your model to set a speed. Link it to a button like 1 or Low, whatever you like and it will work that way. I haven’t figured out how to show fans in Lovelace anyway so I started going that way.  Look at the API for Bond to see how the calls are made. It made sense to me and it’s pretty much the same line with a different speed for low, medium, high or numbered levels.

**Comment by publicpersona31** [comment]
Okay...  It controls the fans perfectly for what I need them to do, and I appreciate the work the author has put in, especially since it looks like IFTTT is going away. 

Your mileage may vary.
