### ISSUE TITLE
Lights no longer work with move to ce85aa4

### ISSUE THREAD

**Issue by codypet** [nguyer/homeassistant-bond-home#29]
The fans work with the upgrade to ce85aa4, but the lights no longer work.  They work fine through the Bond App.  The lights show up as unavailable, but the fans work fine.

Version:
Home Assistant 0.109.6
Bond Home: ce85aa4

Logs:
> Logger: homeassistant.setup
Source: setup.py:249
First occurred: 7:59:40 PM (3 occurrences)
Last logged: 8:00:58 PM

> Unable to prepare setup for platform bond.switch: Platform not found (cannot import name 'SwitchEntity' from 'homeassistant.components.switch' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/switch/__init__.py)).
> Unable to prepare setup for platform bond.light: Platform not found (cannot import name 'LightEntity' from 'homeassistant.components.light' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py)).
> Unable to prepare setup for platform bond.cover: Platform not found (cannot import name 'CoverEntity' from 'homeassistant.components.cover' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/cover/__init__.py)).

![image](https://user-images.githubusercontent.com/17790157/82849146-904d8700-9ec4-11ea-85f2-97f3d441c00b.png)

**Comment by ViolentPoo** [comment]
Home Assistant 0.110 changed how entity class names are done, updating your instance to the latest version should solve your problem.

**Comment by codypet** [comment]
Thanks!
