### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'bond'

### ISSUE THREAD

**Issue by majorsl** [nguyer/homeassistant-bond-home#41]
"No 'version' key in the manifest file for custom integration 'bond'. As of Home Assistant 2021.6, this integration will no longer be loaded." in the logs.

Home Assistant 2021.3 introduced a requirement for a version key in the manifest file.

I hope this is still being developed, it is still better than the built in Bond in several respects.

**Comment by niemyjski** [comment]
If you want to submit a pr for this, we'll merge it. What does this project do better than the built in? I've been using the built in for quite some time now and it's been rock solid.
