### ISSUE TITLE
No fan control

### ISSUE THREAD

**Issue by bkr1969** [nguyer/homeassistant-bond-home#43]
I set up my Bond and can control the light via HA, but, although the fan shows up as an entity, I cannot control it at all.  There are the same two buttons for on and off that the light has, but when I turn it on, it immediately turns back to off. I also have no way of telling its state even if I turn it on manually.  It just always shows as off.

**Comment by bkr1969** [comment]
I just added the Bond to my SmartThings and I can now track the state and control the fan (new ST entity).  Seems odd that it won't work just via the direct HA integration.

**Comment by ViolentPoo** [comment]
> I set up my Bond and can control the light via HA, but, although the fan shows up as an entity, I cannot control it at all.  There are the same two buttons for on and off that the light has, but when I turn it on, it immediately turns back to off. I also have no way of telling its state even if I turn it on manually.  It just always shows as off.

Bond is now a native integration and no longer needs to be installed via HACS. https://www.home-assistant.io/integrations/bond/

**Comment by bkr1969** [comment]
I guess I just posted in the wrong place because I set it up via the UI.  Sorry.

**Comment by niemyjski** [comment]
@nguyer we probably should mark this integration as deprecated and archive the repo.

**Comment by cajuncoding** [comment]
@bkr1969 my fans are working from the native Bond integration as Fan entities just as I would expect….just so you know it may not be an issue with the native Bond integration per-se.

Try posting the official HA forum where you may get alot more traction and support.

**Comment by nguyer** [comment]
Hi @bkr1969. Yeah since there is an official integration available now there hasn't been any more work on this repo in a long time. This project was started before the official integration existed. Hope you get your fans working though.

@niemyjski I agree. I'll do that.
